adadis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('', include("store.urls")),
    path('users/', include("users.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from . views import Index, Details, welcome_page, create_order, confirmed_order, orders, OrderDetails, modification, create_orderCliente, pedidos_Cliente

app_name = "store"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('welcome', welcome_page, name='welcome'),
    path('details/<int:pk>', Details.as_view(), name='details'),
    path('new_order', create_order, name='new_order'),
    path('confirmed_order/<int:order_id>/', confirmed_order, name='confirmed_order'),
    path('orders', orders, name='orders'),
    path('order_detail/<int:pk>', OrderDetails.as_view(), name='order_details'),
    path('modification_order/<int:order_id>', modification, name='modification_order'),
    path('hacer_pedido/', create_orderCliente, name='hacer_pedido'),
    path('tus_pedidos/', pedidos_Cliente, name='tus_pedidos'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from users.models import CustomUser

# Create your models here.
class Product(models.Model):
    titulo = models.CharField(max_length=70)
    descripcion = models.TextField()
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to='store/img', default='store/img/default_image.jpg', null=True)

    def __str__(self):
        return self.titulo

class Order(models.Model):
    pay_choices = (
        ("Efectivo", "Efectivo"),
        ("Debito", "Debito"),
        ("Credito", 'Credito'),
    )

    order_status = (
        ("Pedido Pendiente", "Pedido Pendiente"),
        ("Pedido confirmado", "Pedido confirmado"),
        ("Pago aprobado", "Pago aprobado"),
        ("Pedido preparado","Pedido preparado"),
        ("Pedido Enviado/listo para recoger", "Pedido Enviado/listo para recoger"),
        ("Pedido Entregado", "Pedido Entregado"),
    )

    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=50, default='hola.adadis@outlook.com')
    direccion = models.CharField(max_length=100, default='En Sucursal')
    producto = models.ForeignKey(Product, on_delete=models.CASCADE)
    cantidad = models.IntegerField(null=True)
    precio = models.IntegerField(null=True)
    total = models.IntegerField(null=True)
    metodo_pago = models.CharField(choices=pay_choices, default='Efectivo')
    estado_pedido = models.CharField(choices=order_status, default='Pedido Pendiente')
    
class OrderCliente(models.Model):
    pay_choices = (
        ("Efectivo", "Efectivo"),
        ("Debito", "Debito"),
        ("Credito", 'Credito'),
    )

    nombre = models.CharField(max_length=100, null=True)
    email = models.EmailField(max_length=50, default='hola.adadis@outlook.com')
    direccion = models.CharField(max_length=100, default='En Sucursal')
    producto = models.ForeignKey(Product, on_delete=models.CASCADE)
    cantidad = models.IntegerField(null=True)
    metodo_pago = models.CharField(choices=pay_choices, default='Efectivo')

store/forms.py
from django import forms
from .models import Order, OrderCliente

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['usuario', 'nombre', 'email', 'direccion' ,'producto', 'cantidad', 'metodo_pago', 'estado_pedido']

# class ModifyOrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ['estado']

class PedidoClienteForm(forms.ModelForm):
    class Meta:
        model = OrderCliente
        fields = ['nombre', 'email', 'direccion' ,'producto', 'cantidad', 'metodo_pago']

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.contrib.auth.forms import AuthenticationForm
from .models import Product, Order
from .forms import OrderForm, PedidoClienteForm
from django.contrib import messages
from .models import Order, OrderCliente
import json
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required



# Create your views here.
class Index(generic.ListView):
    model = Product
    template_name = 'store/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form_login"] = AuthenticationForm
        return context

class Details(generic.DetailView):
    model = Product
    template_name = 'store/product_details.html'

def welcome_page(request):
    return render(request, 'store/welcome.html')

'''
def importar():
    with open('data.json', 'r', encoding='utf-8') as file:
        data = json.load(file)
        for item in data:
            fields = item['fields']
            nuevo_producto = Product(
                titulo=fields['titulo'],
                descripcion=fields['descripcion'],
                precio=fields['precio'],
                imagen=fields['imagen'],
            )
            nuevo_producto.save()

'''

# Vendedor
def is_vendedor(user):
    return user.groups.filter(name='vendedor').exists()

@user_passes_test(is_vendedor)
def create_order(request):
    if request.method == 'POST':
        form_order = OrderForm(request.POST)
        if form_order.is_valid():
            order = form_order.save(commit=False)
            order.precio = order.producto.precio
            order.total = order.precio * order.cantidad
            order.save()
            order_id = order.pk 
            return redirect("store:confirmed_order", order_id)
        else:
            messages.error(request, "Hubo un error en el registro del pedido, verifica bien antes de continuar")
    form_order = OrderForm()
    return render(request, "store/new_order.html", {'form_order': form_order})

@user_passes_test(is_vendedor)
def confirmed_order(request, order_id):
    order = Order.objects.get(pk=order_id)
    return render(request, "store/confirmed_order.html", {'order': order})

def is_logistica_o_vendedor(user):
    # return user.has_perm('logistica') or user.has_perm('vendedor')
    return is_logistica(user) or is_vendedor(user)

# Logistica

def is_logistica(user):
    return user.groups.filter(name='logistica').exists()

@user_passes_test(is_logistica_o_vendedor)
def orders(request):
    orders = Order.objects.all()
    return render(request, "store/orders.html", {'orders': orders})

@method_decorator(user_passes_test(is_logistica), name='dispatch')
class OrderDetails(generic.DetailView):
    model = Order
    template_name = 'store/order_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = get_object_or_404(Order, pk=self.kwargs['pk'])
        context['form'] = OrderForm(instance=order)
        return context

    def post(self, request, *args, **kwargs):
        target = Order.objects.get(pk=self.kwargs['pk'])
        form_order = OrderForm(request.POST, instance=target)
        if form_order.is_valid():
            order = form_order.save(commit=False)
            order.precio = order.producto.precio
            order.total = order.precio * order.cantidad
            order.save()
            return redirect("store:modification_order", order_id=self.kwargs['pk'])
        else:
            messages.error(request, "Hubo un error en el registro del pedido, verifica bien antes de continuar")

        return redirect('store:order_details', pk=self.kwargs['pk'])

def modification(request, order_id):
    order = Order.objects.get(pk=order_id)
    return render(request, "store/modification_order.html", {'order': order})

@login_required
def create_orderCliente(request):
    if request.method == 'POST':
        form_order = PedidoClienteForm(request.POST)
        if form_order.is_valid():
            order = form_order.save(commit=False)
            order.precio = order.producto.precio
            order.total = order.precio * order.cantidad
            order.save()
            order_id = order.pk 
            return redirect("store:confirmed_order", order_id)
        else:
            messages.error(request, "Hubo un error en el registro del pedido, verifica bien antes de continuar")
    form_order = PedidoClienteForm()
    return render(request, "store/hacer_pedidos.html", {'form_order': form_order})

@login_required
def pedidos_Cliente(request):
    pedidos = OrderCliente.objects.all()
    return render(request, "store/pedidos_cliente.html", {'pedidos': pedidos} )

store/templates/store/confirmed_order.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>ORDENES DE PEDIDOS</h1>
            </div>
        </div>
    </div>
</div>

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <i class="fa-regular fa-face-smile fa-5x mb-4" style="color: #000000;" aria-hidden="true"></i>
                    <h2 class="card-title product-title">Pedido #{{ order.pk }} creado con éxito</h2>
                    <p class="lead">Aqui te dejamos un  resumen del pedido: </p> 
                    
                    <div class="order-resume">
                        <ul>
                            <li><p><strong>Vendedor:</strong> {{ order.usuario }}</p></li>
                            <li><p><strong>Nombre:</strong> {{ order.nombre }}</p></li>
                            <li><p><Strong>Direccion de Despacho:</Strong> {{ order.direccion }}</p></li>
                            <li><p><strong>Email:</strong> {{ order.email }}</p></li>
                            <li><p><strong>Producto:</strong> {{ order.producto }}</p></li>
                            <li><p><strong>Cantidad:</strong> {{ order.cantidad }}</p></li>
                            <li><p><strong>Numero de Orden</strong> {{ order.pk }}</p></li>
                            <li><p><strong>Estado del Pedido:</strong> {{ order.estado_pedido }}</p></li>
                        </ul>
                    </div>
                    <div>
                        <a href="{% url 'store:new_order' %}" class="button-return">Volver a la página de pedidos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

store/templates/store/hacer_pedidos.html
{% extends 'store/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}<title>{{ object.titulo }}</title>{% endblock %} 

{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>Pedido Nuevo</h1>
            </div>
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center mt-5 mb-5">    
    <div class="col-12 col-lg-5">
        <div class="card">
            <div class="card-body form-new-order">
                <h1>Realiza un nuevo pedido</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form_order|crispy }}
                    <input type="submit" class="btn btn-sucess" value="Realizar Pedido">
                </form>
            </div>
        </div>
    </div>
</div>




<!-- <form method="post">
    {% csrf_token %}
    {{ form_order.as_p }}
    <button type="submit" class="btn btn-sucess">Realizar Pedido</button>
</form> -->
{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}


<!--  Pedidos  -->
<div class="container mt-5">
    <div class="row justify-content-center align-items-stretch">
        {% for producto in object_list %}
        <div class="card mb-4 col-md-3 mx-3 text-product card-products">
            <a href="{% url 'store:details' pk=producto.id %} ">
                {% if producto.imagen %}
                <div class=" d-flex flex-column justify-content-between product-card">
                    <img src="{{ producto.imagen.url }}" alt="{{ producto.titulo }}" class="card-img-top" />
                    <span class="product-price-badge">{{ producto.precio|intcomma }} CLP</span>
                </div>

                {% endif %}
                <div class="card-body d-flex flex-column justify-content-between">
                    <h5 class="card-title mb-0">
                        {{ producto.titulo }}
                    </h5>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

store/templates/store/logout.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body text-center">
            <i class="fa-solid fa-heart-crack fa-5x mb-4" style="color: #ff0000;" aria-hidden="true"></i>
            <h2 class="mb-3">¡Te has desconectado!</h2>
            <p class="lead">Gracias por visitarnos. Esperamos verte pronto de nuevo.</p> <i class="fa-solid fa-hand-wave"></i>
            <i class="fa-solid fa-hand-wave"></i>
            <a href="{% url 'store:index' %}" class="btn button-return">Volver a la página principal</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

store/templates/store/modification_order.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>Confirmacion de Orden Modificada</h1>
            </div>
        </div>
    </div>
</div>

<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body text-center">
                    <i class="fa-regular fa-face-smile fa-5x mb-4" style="color: #000000;" aria-hidden="true"></i>
                    <h2 class="card-title product-title">Pedido #{{ order.pk }} modificado con éxito</h2>
                    <p class="lead">Aqui te dejamos un  resumen del pedido: </p> 
                    
                    <div class="order-resume">
                        <ul>
                            <li><p><strong>Vendedor:</strong> {{ order.usuario }}</p></li>
                            <li><p><strong>Nombre:</strong> {{ order.nombre }}</p></li>
                            <li><p><Strong>Direccion de Despacho:</Strong> {{ order.direccion }}</p></li>
                            <li><p><strong>Email:</strong> {{ order.email }}</p></li>
                            <li><p><strong>Producto:</strong> {{ order.producto }}</p></li>
                            <li><p><strong>Cantidad:</strong> {{ order.cantidad }}</p></li>
                            <li><p><strong>Numero de Orden</strong> {{ order.pk }}</p></li>
                            <li><p><strong>Estado del Pedido:</strong> {{ order.estado_pedido }}</p></li>
                        </ul>
                    </div>
                    <div>
                        <a href="{% url 'store:new_order' %}" class="button-return">Volver a la página de pedidos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

store/templates/store/new_order.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>Pedido Nuevo</h1>
            </div>
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center mt-5 mb-5">    
    <div class="col-12 col-lg-5">
        <div class="card">
            <div class="card-body form-new-order">
                <h1>Realiza un nuevo pedido</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form_order|crispy }}
                    <input type="submit" class="btn btn-sucess" value="Register">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

store/templates/store/order_details.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>Informacion del Pedido # {{ object.pk }}</h1>
            </div>
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center mt-5 mb-5">    
    <div class="col-12 col-lg-5">
        <div class="card">
            <div class="card-body form-order-details">
                <h1>Modificar Pedido #{{ object.pk }}</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-sucess" value="Modificar">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

store/templates/store/orders.html
{% extends 'store/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>ORDENES DE PEDIDOS</h1>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div>
            <a href="{% url 'store:new_order' %}" class="button-new-order">Nuevo Pedido</a>
        </div>
        <div class="">
            <div class="accordion" id="accordionFlushExample">
                {% for order in orders %}
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapse-{{ order.id }}" aria-expanded="false"
                            aria-controls="flush-collapse-{{ order.id }}">
                            <h5 class="card-title product-title">Orden de Pedido #{{ order.id }}</h5>
                        </button>
                    </h2>
                    <div id="flush-collapse-{{ order.id }}" class="accordion-collapse collapse"
                        data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body ">
                            <div class="order-resume">
                                <ul>
                                    <li>
                                        <p><strong>Vendedor:</strong> {{ order.usuario }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Nombre:</strong> {{ order.nombre }}</p>
                                    </li>
                                    <li>
                                        <p><Strong>Direccion de Despacho:</Strong> {{ order.direccion }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Email:</strong> {{ order.email }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Producto:</strong> {{ order.producto }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Cantidad:</strong> {{ order.cantidad }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Estado del Pedido:</strong> {{ order.estado_pedido }}</p>
                                    </li>
                                </ul>
                            </div>
                            <a href="{% url 'store:order_details' pk=order.pk %}" class="button-order-details">Modificar
                                Pedido</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>



{% endblock %}

store/templates/store/pedidos_cliente.html
{% extends 'store/base.html' %}
{% load static %}
{% load humanize %}

{% block title %}<title>{{ object.titulo }}</title>{% endblock %}

{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content-order">
                <h1>TUS PEDIDOS</h1>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div>
            <a href="{% url 'store:hacer_pedido' %}" class="button-new-order">Nuevo Pedido</a>
        </div>
        <div class="">
            <div class="accordion" id="accordionFlushExample">
                {% for i in pedidos %}
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#flush-collapse-{{ order.id }}" aria-expanded="false"
                            aria-controls="flush-collapse-{{ order.id }}">
                            <h5 class="card-title product-title">Orden de Pedido #{{ order.id }}</h5>
                        </button>
                    </h2>
                    <div id="flush-collapse-{{ order.id }}" class="accordion-collapse collapse"
                        data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body ">
                            <div class="order-resume">
                                <ul>
                                    <li>
                                        <p><strong>Nombre:</strong> {{ i.nombre }}</p>
                                    </li>
                                    <li>
                                        <p><Strong>Direccion de Despacho:</Strong> {{ i.direccion }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Email:</strong> {{ i.email }}</p>
                                    </li>
                                    <li>
                                        <p><strong>Producto:</strong> {{ i.producto }}</p>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}

store/templates/store/product_details.html
{% extends 'store/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

{% block title %}<title>{{ object.titulo }}</title>{% endblock %} 

<div class="container mt-5 mb-5">
    <div class="row justify-content-center align-items-center">
      <div class="col-md-4">
        <div class="card">
          <img src="{{ object.imagen.url }}" class="card-img-top imgCardProducto" alt="Fissure in Sandstone" />
        </div>
      </div>
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title product-title">{{ object.titulo }}</h5>
            <p class="card-text product-description">{{ object.descripcion }}</p>
            <p class="product-price">Precio: ${{ object.precio|intcomma }}</p>
           
            <div class="row align-items-center">
              <div class="col-md-4">
                <div class="input-group">
                  <span class="input-group-text">Cantidad</span>
                  <button class="btn btn-outline-secondary button-amount" type="button" id="decrement-btn">-</button>
                  <input type="text" class="form-control text-center" id="cantidad" value="1" readonly>
                  <button class="btn btn-outline-secondary button-amount" type="button" id="increment-btn">+</button>
              </div>
              
              </div>
              <div class="col-md-8">
                <a href="#!" class="btn me-3 font-button button-cart">Añadir al Carrito</a>
                <a href="#!" class="btn font-button button-buy">Comprar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const incrementBtn = document.getElementById("increment-btn");
      const decrementBtn = document.getElementById("decrement-btn");
      const cantidadInput = document.getElementById("cantidad");
  
      incrementBtn.addEventListener("click", function () {
        let cantidad = parseInt(cantidadInput.value);
        cantidadInput.value = cantidad + 1;
      });
  
      decrementBtn.addEventListener("click", function () {
        let cantidad = parseInt(cantidadInput.value);
        if (cantidad > 1) {
          cantidadInput.value = cantidad - 1;
        }
      });
    });
  </script>


{% endblock %}

store/templates/store/welcome.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}

<div class="slider-container">
    <div class="slider">
        <div class="slide">
            <img src="{% static '/store/img/slider1.jpg' %}" alt="">
            <div class="slide-content">
                <h1>BIENVENIDOS</h1>
            </div>
        </div>
        <div class="slide">
            <img src="{% static '/store/img/slider2.jpg' %}" alt="">
            <div class="slide-content">
                <h1></h1>
            </div>
        </div>
        <div class="slide"><img src="{% static '/store/img/slider3.jpg' %}" alt=""></div>
       
    </div>
</div>

<script>
    const slider = document.querySelector('.slider');
    let slideIndex = 0;

    function showSlide(index) {
        slider.style.transform = `translateX(-${index * 100}%)`;
    }

    function nextSlide() {
        slideIndex = (slideIndex + 1) % slider.childElementCount;
        showSlide(slideIndex);
    }

    setInterval(nextSlide, 8000);
    showSlide(slideIndex);

</script>

{% endblock %}