adadis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('', include("store.urls")),
    path('users/', include("users.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.contrib import admin
from django.urls import path
from . views import Index, Details, welcome_page, create_order, confirmed_order, orders, OrderDetails, modification, create_orderCliente, pedidos_Cliente

app_name = "store"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('welcome', welcome_page, name='welcome'),
    path('details/<int:pk>', Details.as_view(), name='details'),
    path('new_order', create_order, name='new_order'),
    path('confirmed_order/<int:order_id>/', confirmed_order, name='confirmed_order'),
    path('orders', orders, name='orders'),
    path('order_detail/<int:pk>', OrderDetails.as_view(), name='order_details'),
    path('modification_order/<int:order_id>', modification, name='modification_order'),
    path('hacer_pedido/', create_orderCliente, name='hacer_pedido'),
    path('tus_pedidos/', pedidos_Cliente, name='tus_pedidos'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [
    path('login/', views.view_login, name="login"),
    path('register/', views.PublicRegisterView.as_view(), name='register'),
    path('register_confirmation', views.EmailConfirmationView.as_view(), name='email_confirmation'),
    path('register_adm/', views.superuser_form, name='register-adm'),
    path("logout/", auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name="logout"),
]

users/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser, User

# Create your models here.
class CustomUser(AbstractUser):
    # nombre = models.CharField(max_length=50)
    rut = models.CharField(max_length=12)
    # email = models.EmailField()
    # grupo = models.CharField(max_length=50)

    def __str__(self):
        # return self.nombre
        return self.username

# class CustomUser2(AbstractUser):
#     username = None
#     rut = models.CharField(max_lenth=12, unique=True)

#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = []

#     def __str__(self):
#         self.rut

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from users.models import CustomUser


class SuperRegisterForm(UserCreationForm): 
    rol  = (
        ('staff', 'staff'),
        ('vendedor', 'vendedor'),
        ('logistica', 'logistica')
    )
    email = forms.EmailField()
    type_user = forms.ChoiceField(choices=rol)

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', 'type_user']

class RegistrationForm(forms.ModelForm):
    first_name = forms.CharField(label='Full Name', max_length=150)

    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'rut', 'email']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test
from .forms import SuperRegisterForm, RegistrationForm
from django.contrib.auth.models import Group
from django.views import generic, View
from django.contrib import messages
from django.utils.crypto import get_random_string
from django.core.mail import send_mail
from django.conf import settings
from django.urls import reverse_lazy

# Create your views here.
def view_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.has_perm('logistica'):
                return redirect('store:orders')
            else:    
                return redirect('store:welcome')
    
    return redirect('store:index')


def public_registration(request):
    return render(request, 'public_registration.html')
    
class PublicRegisterView(generic.edit.FormView):
    template_name = 'users/form_render.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:email_confirmation')

    def form_valid(self, form):
        user = form.save(commit=False)
        password = get_random_string(length=6)
        user.set_password(password)
        user.save()

        # Envía el correo con la contraseña aleatoria
        subject = 'Contraseña de confirmación'
        message = f'Su contraseña de confirmación es: {password}'
        from_email = settings.EMAIL_HOST_USER  
        recipient_list = [user.email]
        send_mail(subject, message, from_email, recipient_list)
        return super().form_valid(form)

class EmailConfirmationView(View):
    template_name = 'users/email_confirmation.html' 

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
def is_superuser(user):
    return user.is_superuser

@user_passes_test(is_superuser)
def superuser_form(request):
    if request.method == "POST":
        form = SuperRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            chosen_rol = form.cleaned_data["type_user"]
            if chosen_rol == "staff":
                rol = Group.objects.get(name="staff")
            elif chosen_rol == "vendedor":
                rol = Group.objects.get(name="vendedor")
            elif chosen_rol == "logistica":
                rol = Group.objects.get(name="logistica")
            user.save()
            user.groups.add(rol)

            return redirect('store:index')

        else:
            messages.error(request, "Error en el registro")
    form = SuperRegisterForm()
    return render(request, 'users/superuser_form.html', {'form':form})

users/templates/users/email_confirmation.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="row d-flex justify-content-center align-items-center" style="height: 300px;">
    <div class="col m-5 text-center">
        <h2 class="my-3">Cuenta creada</h2>
        <p>Tu contraseña ha sido enviada a tu correo.</p>
    </div>
</div>
{% endblock content %}

users/templates/users/form_render.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-12 col-lg-5">
        <div class="card">
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" class="btn btn-sucess" value="Register">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card">
          <div class="card-body text-center">
            <i class="fa fa-check-circle text-success fa-5x mb-4" aria-hidden="true"></i>
            <h2 class="mb-3">¡Te has desconectado!</h2>
            <p class="lead">Gracias por visitarnos. Esperamos verte pronto de nuevo.</p>
           
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/superuser_form.html
{% extends 'store/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div style="display:flex; justify-content:center; align-items:center;">
    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
            {{form|crispy}}
        </div>
        <button type="submit" class="btn btn-success">Registro</button>
    </form>
    <div>
        <small>
            Tienes ya una cuenta? <a href="{% url 'users:login' %}">Log in</a>
        </small>
    </div>

</div>
{% endblock %}